### ISSUE TITLE
Add initial net config to kayak

### ISSUE THREAD

**Issue by mir07** [omniosorg/kayak#1]
Hi all,

I think it is not very easy for new users coming to Omnios from various other distros to make the initial network configuration so I have written a small tool in Python to remedy this obstacle. The script is tested and runs on all Omnios as of r151014. I have tested on r151014 and r151022

The script is not ment to be the swiss army knife for configuring networks on Omnios so there is no support for vnic, vlan, and aggregates. It will only support configuring a single nic given the
user the option for dhcp and static setup. The user is also asked whether to configure dns in which case the user is asked for an IP.

Currently it will only handle ethernet but IPoIB is on my todo list. The script can be downloaded here: http://git.datanom.net/netconf.git/

**Comment by oetiker** [comment]
hi @mir07,

would you like to help maintaining kayak ?

cheers
tobi

**Comment by mir07** [comment]
Yes, but I might need some help with the low-level stuff. I have some ideas to extend its functionality.

**Comment by citrus-it** [comment]
@mir07 We have a test bloody installer available which implements this feature.

![image](https://user-images.githubusercontent.com/29426693/30330394-7b57fcae-97c4-11e7-90c4-fa913905b473.png)

Please could you test this to see if it meets your requirement and provide any feedback.

It can be downloaded from https://downloads.omniosce.org/media/.test/omniosce-bloody-20170912.iso

Thanks.

**Comment by mir07** [comment]
I was trying to download the image for testing but received a 404?

**Comment by citrus-it** [comment]
Try https://downloads.omniosce.org/media/bloody/.test/omniosce-bloody-20170916.iso
New media is being built over the next day or two but this one contains the new menu.

**Comment by mir07** [comment]
That works. Thanks

**Comment by mir07** [comment]
I don't think the network configuration part will work if one or both of these situations occurs:
1) Installation is done on a machine only containing infiniband
2) Installation is done on a machine containing infiniband and infiniband is listed in the menu displayed to the user

**Comment by mir07** [comment]
To filter out infiniband use this instead to find ethernet links:
dladm show-phys -p -o link,media | grep -v Infiniband|cut -f1 -d:

**Comment by citrus-it** [comment]
Thanks, I'll have a look.

**Comment by citrus-it** [comment]
Closing.
