### ISSUE TITLE
Support for virtual terminals

### ISSUE THREAD

**Issue by ghost** [omniosorg/kayak#11]
Can the OmniOSce installer also present an option to enable support for virtual terminals?
The following (by Volker Brandt) can be used.

svcs console-login
svcadm enable vtdaemon
svcadm enable console-login:vt2
svcadm enable console-login:vt3
svcadm enable console-login:vt4
svcadm enable console-login:vt5
svcadm enable console-login:vt6
svcs console-login vtdaemon
svccfg -s vtdaemon setprop options/hotkeys=true
svccfg -s vtdaemon setprop options/secure=false
svcadm refresh vtdaemon
svcadm restart vtdaemon

**Comment by citrus-it** [comment]
We have a test bloody installer available which implements this feature.

![image](https://user-images.githubusercontent.com/29426693/30330303-3e8cae82-97c4-11e7-9beb-0f85173232ef.png)

Please could you test this to see if it meets your requirement?

It can be downloaded from https://downloads.omniosce.org/media/.test/omniosce-bloody-20170912.iso

**Comment by citrus-it** [comment]
Closing.
