### ISSUE TITLE
/bin/dmesg is a symlink to /sbin/dmesg, which is missing

### ISSUE THREAD

**Issue by ghost** [omniosorg/kayak#124]
Booting into the installer and escaping to shell, I wanted to see the kernel messages and wasn't unable to -- /var/adm/messages is missing, and /bin/dmesg is linked to /sbin/dmesg, which is simply isn't there.

Tried omniosce-bloody-20190703.iso, and understand that it's unsupported version, though the issue should be common?

**Comment by citrus-it** [comment]
Thanks for the report, I'm working on a fix which will be in the r151032 release.
