### ISSUE TITLE
Can no longer force 4K sector size for the root pool

### ISSUE THREAD

**Issue by github-kjsj** [omniosorg/kayak#128]
I believe I've run into a regression going from the r151028 to the r151030 installer, in that the option to force 4K sector sizes for the root pool is no longer honored: after rebooting into the new system, I find that the ashift for the pool is 9 (with r151028, it's correctly being set as 12). I originally noticed this using physical hardware, but I'm able to also reproduce it under VirtualBox. (Also, I'm using omniosce-r151028b.iso for r151028 and omniosce-r151030h.iso for r151030.)

Let me know if there are any additional details I can provide (please bear with me, though, I'm currently a bit of novice when it comes to OmniOS)!

**Comment by citrus-it** [comment]
Thanks for the report - I'll build some new installation media for r151030 with a fix in.

**Comment by citrus-it** [comment]
Please can you try: https://downloads.omniosce.org/media/r151030/omniosce-r151030s.iso ?

**Comment by github-kjsj** [comment]
Looks like that did the trick! Tested on VirtualBox and a physical box, and in each case, the ashift for rpool was set to the forced value. Thanks!

**Comment by citrus-it** [comment]
Great, thanks for letting me know.
