### ISSUE TITLE
BE of freshly installed OmniOS has no UUID

### ISSUE THREAD

**Issue by hadfl** [omniosorg/kayak#2]
the BE of a freshly installed OmniOS has no UUID:
```
hadfl@mars:~$ beadm list -H
omnios;;;;27661312;static;1499278066
```

Therefore e.g. installing a native zone fails:
```
hadfl@mars:~$ sudo zoneadm -z testzone install
Sanity Check: Looking for 'entire' incorporation.
ERROR: unable to determine global zone boot environment.
ERROR: cannot install zone testzone
```

In earlier installers, OmniOS was installed to `omniosvar` and then a new BE has been created after installation.

Workaround until fixed:
Create a new BE manually after installing OmniOS.

**Comment by ptribble** [comment]
There's a much simpler workaround for when this happens. All you need to do is add a zfs property to the BE. Like so:

/usr/sbin/zfs set org.opensolaris.libbe:uuid=`uuidgen` rpool/ROOT/omnios

**Comment by hadfl** [comment]
Oh, just realised it has been discussed on the mailing list. Does this patch look feasible?

```
diff --git a/install_help.sh b/install_help.sh
index 7ad5ab1..da377e2 100644
--- a/install_help.sh
+++ b/install_help.sh
@@ -115,6 +115,8 @@ BuildBE() {
   $GRAB $MEDIA | pv -B 128m -w 78 | $DECOMP | zfs receive -u $RPOOL/ROOT/omnios
   zfs set canmount=noauto $RPOOL/ROOT/omnios
   zfs set mountpoint=legacy $RPOOL/ROOT/omnios
+  zfs set org.opensolaris.libbe:uuid=`LD_LIBRARY_PATH=/mnt/lib:/mnt/usr/lib /mnt/usr/bin/uuidgen` $RPOOL/ROOT/omnios
+  zfs set org.opensolaris.libbe:policy=static $RPOOL/ROOT/omnios
   log "Cleaning up boot environment"
   beadm mount omnios /mnt
   ALTROOT=/mnt
```

**Comment by ptribble** [comment]
I thought this had come up.

That doesn't look quite right, the uuidgen is called from /mnt which isn't mounted until a few lines later - so if you move the 2 zfs set commands to just after the beadm mount command it ought to work.

**Comment by hadfl** [comment]
my bad. didn't check thoroughly when `/mnt` is mounted.

-> https://github.com/omniosorg/kayak/pull/3
