### ISSUE TITLE
vioscsi(4D) driver not supported by the installation media despite being announced as available

### ISSUE THREAD

**Issue by draga79** [omniosorg/kayak#289]
Hi, I've been trying to install OmniOS (both r151050 and Bloody) inside a Hetzner VM. It just doesn't detect the virtual disk as it's a virtio-scsi device.

I've performed the same test with a Netcup and Proxmox VM, and had the same problem. The only way to install it is changing to the virtio driver, which can be less efficient and/or impossible (Hetzner doesn't allow to change the driver).

This is strange, as it had been announced as available here: https://forums.servethehome.com/index.php?threads/omnios-151048-stable-opensource-solaris-fork-unix.42093/

Thank you.

**Comment by citrus-it** [comment]
Thanks for the report. The driver was not actually in the installation miniroot which was a mistake. I have opened a pull request to correct this oversight at https://github.com/omniosorg/kayak/pull/288
and we'll get updated r50 media built.

**Comment by citrus-it** [comment]
Updated r151050e media are now available via https://omnios.org/download on the Swiss mirror (they will take another hour or so to make it to the US mirror). Please let us know if these work any better for you.

**Comment by draga79** [comment]
Hi, that was fast! Thank you, I really appreciate it.
I can confim it works on Proxmox with virtio-scsi controller. I'm going to test it on the other VMs.

**Comment by draga79** [comment]
Yes, your English is clear and understandable. Here is a slightly polished version:

Ok, I've performed some other tests:

Everything's fine with Proxmox.
Everything's fine with Netcup.
It's not working with Hetzner VM. On Hetzner, I'm installing OmniOS by booting in rescue mode and, from there, using QEMU with a command line similar to this:

```sh
qemu-system-x86_64 -smp 2 -m 2048 -nic user -boot d -cdrom omnios.iso -device virtio-scsi-pci,id=scsi0 -drive file=/dev/sda,if=none,format=raw,discard=unmap,aio=native,cache=none,id=someid -device scsi-hd,drive=someid,bus=scsi0.0 -vnc 127.0.0.1:0 -k en-us
```

It installs and runs perfectly (albeit slowly). But when rebooting the VM (so booting without QEMU), there's a boot loop. Enabling verbose boot, here's what happens (I've recorded a short video): https://youtu.be/F-yAiu6YXg4

It seems unable to detect and mount the root file system.

I'm keeping the VM running. Please let me know if I can be of any help.

Thank you.

**Comment by draga79** [comment]
Update: I've asked Hetzner to provide the ISO and they did it. I've tried to install directly into the VPS, but the installer can't see the virtual disk. According to a Linux VPS, it should be a virtio-scsi.
