### ISSUE TITLE
Text-based installer failing to execute find-and-install (r151026)

### ISSUE THREAD

**Issue by kraileth** [omniosorg/kayak#68]
Hope this is the right place to post to (I'm just having my initial contact with the Illumos world). I downloaded an ISO for r151026 and tried to do an installation in VirtualBox. Out of curiosity I chose the old installer and when I selected "Find disks, create rpool, and install OmniOSce", an error message shows up for the blink of an eye. I kept the "1" key pressed so that the message was displayed over and over again so that I could finally read it:

`/kayak/installer/kayak-menu[254]: /kayak/installer/find-and-install: not found [No such file or directory]`

It looks like the script is present here in the repo. But obviously there's something wrong on the install media.

I rebooted and used the new installer (which is quite nice, BTW!) to get OmniOS put on the virtual disk. Worked like a charm. Still I thought that I might bring this to the developer's attention in case it hasn't been known so far (only newbies don't do a custom installation, right? ;)).

**Comment by citrus-it** [comment]
Thanks for the report, I've raised a fix for this which will be in the next media that we build.
